const ROLES = {
  CITIZEN: "CITIZEN",
  STAFF: "STAFF",
  ADMIN: "ADMIN",
};

const ISSUE_STATUS = {
  CREATED: "CREATED",
  UNDER_REVIEW: "UNDER_REVIEW",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
};

const ISSUE_EVENT_TYPE = {
  CREATED: "CREATED",
  STATUS_CHANGED: "STATUS_CHANGED",
  NOTE_ADDED: "NOTE_ADDED",
  INFO_REQUESTED: "INFO_REQUESTED",
  INFO_RECEIVED: "INFO_RECEIVED",
  ASSIGNED: "ASSIGNED",
  UNASSIGNED: "UNASSIGNED",
  REOPENED: "REOPENED",
};

const ALL_ISSUE_STATUSES = Object.values(ISSUE_STATUS);

module.exports = {
  ROLES,
  ISSUE_STATUS,
  ISSUE_EVENT_TYPE,
  ALL_ISSUE_STATUSES,
};